### ISSUE TITLE
smoderp1d wps process: return hydrogram

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#103]
Currenty WPS `smoderp1d` process is producing only `profile` output. Hydrogram is commented out (https://github.com/storm-fsv-cvut/smoderp2d/blob/master/bin/wps/pywps/processes/smoderp1d.py#L102). 

@pesekon2 Where hydrogram is stored? Is it `tests/data/output/point001.csv`?

**Comment by pesekon2** [comment]
> Where hydrogram is stored? Is it `tests/data/output/point001.csv`?

Yes, it is.
