### ISSUE TITLE
The purpose of the Size object

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#106]
Does anyone have a clue what is the purpose of the Size object defined [here in general.py](https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/core/general.py#L5-L15)? I have two problems with that class:

* the class has just one method and that is broken - you cannot call `self` in a `staticmethod` (that's actually what brought my attention to this object when I was searching for something else)
* Although quite some classes inherit from `Size`, the object's only method is not actually used anywhere

As the class doesn't seem having any meaning for the code, I actually vote to delete it, but don't want to destroy work that somebody prepared for some cryptic future operations. Otherwise, I can fix it as the fix would be just to delete the `staticmethod` operator.

**Comment by jerabekjak** [comment]
Well, we have got issues with RAM usage. So this class supposed to be only for the optimization. You can have a look at how much memory will be used by each of the main objects in core/. I wanted to make them (the classes) make as small as possible, and for that, I thought I'll need to see their RAM usage.  
Actually, I do not remember if I've ever used it...I vote to DELETE IT as well.

**Comment by pesekon2** [comment]
Okay, thanks. 

Closing the issue with 9dca6cfd34195a830af93d9fdf8a106b317d9ebd. In the case we would like to do some Jesus magic with that and resurrect it later, we can find the deleted code in the connected commit and the explanation here.
