### ISSUE TITLE
nogis: introduce slope width

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#113]
Config:

```
[domain]
slope_width: 1 # required
```

- [x] Profile:

  * maximalSurfaceFlow
  * totalRunoff

  times `slope_width`

- [x] Hydrograph:

  * @jerabekjak To be defined.

**Comment by pesekon2** [comment]
Implemented into profile in c6da485dc7d79ce6db43a0055917f4ab0af025ac

**Comment by jerabekjak** [comment]
Should I do the same in hydrographs? As mention in the first comment?

**Comment by pesekon2** [comment]
Yes, please, if you can. 

But if you don't have time or something, just let me know what should be multiplied and I can try it.

**Comment by landam** [comment]
@pesekon2 @jerabekjak Please clarify what is need in order to close the issue. Thanks.

**Comment by jerabekjak** [comment]
I've done it in the commit cf7ff7adea9afa108fea9a2d43e8f7888e231a95 to a new branch. Please review if its a good solution.

**Comment by jerabekjak** [comment]
@kavkapet Should be the infiltration and rainfall also multiplied with the slope width? The multiplication is done aside from the te water balance computation so the water balance computation should not be affected.

**Comment by jerabekjak** [comment]
multiply the cumulative value which does to hydrograph by slope width (which differs from 1 only in case of nogis provider)
see commit 8f182e28fd0561a36812c5d9fc8fc1303cd66ffc
