### ISSUE TITLE
Cleanup of the cumulative max class

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#119]
the cumulative max arrays and updating methods are just a mess which causes error in saved results although the results are computed correctly.

Cleanup of the cumulative max values

**Comment by jerabekjak** [comment]
vol_sur_r was remover since the remaning volume in calculated elsewhere in the portprocessing method in base provider
4e8a677b5cb765ab43da4597c613107434c2fb9c

**Comment by landam** [comment]
@jerabekjak @pesekon2 Can be merged into master?

**Comment by jerabekjak** [comment]
hope so, dont know if it was tested in the wps. if yes, we can marge `issue_119_cleanup_cumulative_max` into master.
