### ISSUE TITLE
Error when calling classFactiry()

### ISSUE THREAD

**Issue by VCH-HGP** [storm-fsv-cvut/smoderp2d#123]
Dobrý den, nemám moc vhled do pythonu a tak se předem omlouvám za možná zcela zřejmý  dotaz způsobený nedostatkem mých zkušeností. Nicméně při pokusu spuštění pluginu v QGIS 3.10 Coruna se mi zobrazí hláška níže a nelze spustit plugin. Složku jsem nakopíroval z bin-qgis složky do python pluginů do hlavního adresáře QGISu. Kompilaci resourse.qrc jsem dle návodu udělal, ale pak jsem si všiml, že tam již je od rozbalení raru. Do adresáře QGISu jsem zkoušel složku nahrát jak s resourse.py od z raru tak mnou zkomilovaného a v obou případech se vyskytuje tato hláška.
Děkuji za jakoukoliv radu.
Václav

Couldn't load plugin 'smoderp2d-plugin' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'smoderp2d' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\smoderp2d-plugin\__init__.py", line 35, in classFactory
    from .smoderp_2D import Smoderp2D
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\smoderp2d-plugin\smoderp_2D.py", line 31, in 
    from .smoderp_2D_dockwidget import Smoderp2DDockWidget
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\smoderp2d-plugin\smoderp_2D_dockwidget.py", line 40, in 
    from smoderp2d import QGISRunner
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'smoderp2d'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.2-A Coruña A Coruña, d4cd3cfe5a 

Python Path:
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins\smoderp2d-plugin\..\..\..
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python
C:/Users/chroustovskyv/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/chroustovskyv/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/chroustovskyv/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by landam** [comment]
@VCH-HGP Dobry den, dekujeme za report. Bohuzel neni QGIS plugin jeste plne funkcni.

**Comment by pesekon2** [comment]
@VCH-HGP: Dobrý den. Omlouvám se, že jsem nedal vědět, když se QGIS plugin konečně zprovoznil, ale narazil jsem na issue až nyní. QGIS plugin by již měl být funkční. Prosím, ozkoušejte jej ještě jednou -- pokud budou s jeho použitím ještě nějaké problémy, rádi se je pokusíme vyřešit.

**Comment by pesekon2** [comment]
As I believe this has been solved meanwhile, I am closing the issue. Feel free to reopen it if you find it still valid.
