### ISSUE TITLE
ArcGIS provider: review differences 

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#144]
Review differences between new version of ArcGIS provider (`jandevaty-patch-1`) and old version (`master`).

**Comment by pesekon2** [comment]
Variables with different values: 

- [ ] array_points
- [ ] combinatIndex
- [ ] mat_a
- [ ] mat_aa
- [ ] mat_b
- [ ] mat_dem
- [ ] mat_hcrit
- [ ] mat_n
- [ ] mat_nan
- [ ] mat_pi
- [ ] mat_ppl
- [ ] mat_slope
- [ ] outdir
- [ ] points
- [ ] streams
- [ ] streams_loc
- [ ] temp

Variables that appear only in one of the pickles: 

- [ ] NoDataValue
- [ ] bc
- [ ] br
- [ ] c
- [ ] dx
- [ ] dy
- [ ] pixel_area
- [ ] r
- [ ] rc
- [ ] rr
- [ ] xllcorner
- [ ] yllcorner

**Comment by landam** [comment]
Suggestions:

- [ ] remove all path-oriented variables from saved data

**Comment by pesekon2** [comment]
> remove all path-oriented variables from saved data (temp, stream_loc, points)

I agree. I think that they could be mentioned in logs, but they are not necessarily in the saved data. 

> remove all variables which can be set in config (?)

The same opinion as on the first point.

**Comment by jerabekjak** [comment]
Suggestions (for investigation of differences in `rr` and `rc` in the old and new version): 
This strange thing:
https://github.com/storm-fsv-cvut/smoderp2d/blob/f167739e1e8c6a4f30079600436e34d1c7b44201/smoderp2d/providers/base/data_preparation.py#L397
was suppose to reduce size of `mat_boundary`. 
The `rr` and `rc` lists are based on this  `mat_boundary`. I suggests to comment the line 397 in the link above to investigate the differences in the `mat_boundary` between versions. 
However, I am not able to run smoderp in arcmap in neither the branches (master, jandevaty-path-1)...
Maybe someone can similar archive as [data_comp.zip](https://github.com/storm-fsv-cvut/smoderp2d/files/10546523/data_comp.zip) and share it here with me.

**Comment by landam** [comment]
Stream comparision:

```
'stream_segment_id': [1, 2, 3],
b'fid':              [1, 2, 3]
'channel_shape_id': [1, 4, 1],
b'number':          [1, 1, 1]
'stream_segment_next_down_id': [3.0, 1.0, -1.0],
b'to_node':                    [3.0, 1.0, -9999.0]
'stream_segment_length': [182.32085582937245, 56.82613852420922, 174.65664760832007],
b'length':               [182.32085598560315, 56.82611174117744, 174.59185523227038]
'stream_segment_inclination': [0.029009297790127793, 0.023128441138084592, 0.03129740593839327],
'slope':                      [0.02712372602976437,  0.02323747947920727,  0.03313618971626179],
'channel_profile': ['shape0', 'triangle1', 'shape0'],
b'smoderp':        ['shape0', 'shape0', 'shape0']
'channel_shapetype': [1, 2, 1],
b'shapetype':        [1, 1, 1]
'channel_bottom_width': [1.1, 0.0, 1.1],
b'b':                   [1.1, 1.1, 1.1]
'channel_bank_steepness': [2.1, 2.0, 2.1],
b'm':                     [2.1, 2.1, 2.1]
'channel_bed_roughness': [0.03, 0.03, 0.03],
b'roughness':            [0.03, 0.03, 0.03]
'channel_q365': [0, 0, 0]}
b'q365':        [0, 0, 0]
```

**Comment by landam** [comment]
@jandevaty mat_b,n... try https://pro.arcgis.com/en/pro-app/latest/tool-reference/environment-settings/nodata.htm `Globals.NoDataValue`
