### ISSUE TITLE
Output data layout differs based on providers

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#153]
ArcGIS: 

```
.
└── output
    ├── control
    │   ├── crillvout_m3.asc
    │   ├── csheetvoutm3.asc
    │   ├── cvin_m3.asc
    │   ├── mqrill_m3_s.asc
    │   ├── mqsheet_m3_s.asc
    │   ├── mwlevel_m.asc
    │   ├── mwlevelrill_m.asc
    │   ├── surret_m.asc
    │   └── widthrill.asc
    ├── cinfil_m3.asc
    ├── crain_m3.asc
    ├── cvsur_m3.asc
    ├── massbalance.asc
    ├── mqsur_m3_s.asc
    ├── mrsearstr_pa.asc
    ├── mvel_m_s.asc
    ├── reachfid.asc
    ├── stream.csv
    └── volrest_m3.asc
```

CMD:

```
.
├── control
│   ├── cRillVOut_m3.asc
│   ├── cSheetVOutM3.asc
│   ├── cVIn_M3.asc
│   ├── mQRill_m3_s.asc
│   ├── mQsheet_m3_s.asc
│   ├── mWLevel_m.asc
│   ├── mWLevelRill_m.asc
│   ├── surRet_M.asc
│   └── widthRill.asc
├── core
│   ├── cInfil_m3.asc
│   ├── cRain_m3.asc
│   ├── cVsur_m3.asc
│   ├── massBalance.asc
│   ├── mQsur_m3_s.asc
│   ├── mrSearStr_Pa.asc
│   ├── mVel_m_s.asc
│   ├── reachFid.asc
│   └── volRest_m3.asc
├── point000.csv
├── point001.csv
├── point002.csv
└── point003.csv
```

**Comment by landam** [comment]
Draft suggestion:

```
.
└── output
    ├── control
    │   ├── crillvout_m3.asc
    │   ├── csheetvoutm3.asc
    │   ├── cvin_m3.asc
    │   ├── mqrill_m3_s.asc
    │   ├── mqsheet_m3_s.asc
    │   ├── mwlevel_m.asc
    │   ├── mwlevelrill_m.asc
    │   ├── surret_m.asc
    │   └── widthrill.asc
    ├── cinfil_m3.asc
    ├── crain_m3.asc
    ├── cvsur_m3.asc
    ├── massbalance.asc
    ├── mqsur_m3_s.asc
    ├── mrsearstr_pa.asc
    ├── mvel_m_s.asc
    ├── reachfid.asc
    ├── stream.csv
    ├── volrest_m3.asc
    ├── point000.csv
    ├── point001.csv
    ├── point002.csv
   └── point003.csv
```

**Comment by kavkapet** [comment]
my suggestion, sorry for some comments in Czech
.
└── output
    ├── mqsur_m3_s.asc
    ├── mrsearstr_pa.asc
    ├── mvel_m_s.asc
    ├── stream.shp 		# k vrstvě finálních toků připojit tabulku co se jmenuje stream.csv
    ├── cvsur_m3.asc
    ├── mwlevel_m.asc
    ├── control_points.shp	# body uvnitř řešení ??? zdali k nim umíme přidat něco jako 3D hodnotu, tzn data z pointXXX.dat
    ├── control_points
	point000.csv
	    ├── point001.csv
	    ├── point002.csv
    	    └── point003.csv

    ├── control
       	├── crillvout_m3.asc
       	├── csheetvoutm3.asc
       	├── cvin_m3.asc
       	├── mqrill_m3_s.asc
       	├── mqsheet_m3_s.asc
       	├── cvrill_m3.asc
       	├── cvsheet_m3.asc
       	├── mwlevelrill_m.asc 	# to nevím co je - asi maximální výška rýhy, to asi nepotřebujeme pokud máme widthrill
       	├── surret_m.asc
       	├── widthrill.asc 	# maximální šířka rýhy (doufám)
    	├── cinfil_m3.asc	# přepočítat na mm výšky
    	├── crain_m3.asc	# přepočítat na mm výšky
    	├── volrest_m3.asc	# přepočítat na mm výšky
  	├── massbalance.asc
  	├── hcrit.asc
        ├── reachfid.asc spojit s state.asc (výhledově, zatím nechat dohromady)

├── temp
	├── all spatial data drom dpre
       	├── stream.csv  	# dokud se nevyřeší připojení na stream.shp
       	├── cvrill_m3.asc
       	├── cvsheet_m3.asc
       	├── mwlevelrill_m.asc 	# to nevím co je - asi maximální výška rýhy, to asi nepotřebujeme pokud máme widthrill
       	├── surret_m.asc
       	├── widthrill.asc 	# maximální šířka rýhy (doufám)
    	├── cinfil_m3.asc	# přepočítat na mm výšky
    	├── crain_m3.asc	# přepočítat na mm výšky

**Comment by landam** [comment]
Updated solution (newly added items moved to #173):

```
.
└── output
    ├── mqsur_m3_s.asc
    ├── mrsearstr_pa.asc
    ├── mvel_m_s.asc
    ├── cvsur_m3.asc
    ├── mwlevel_m.asc
    ├── control_points
	    ├── point000.csv
	    ├── point001.csv
	    ├── point002.csv
    	    └── point003.csv
    ├── control
       	├── crillvout_m3.asc
       	├── csheetvoutm3.asc
       	├── cvin_m3.asc
       	├── mqrill_m3_s.asc
       	├── mqsheet_m3_s.asc
       	├── cvrill_m3.asc
       	├── cvsheet_m3.asc
       	├── mwlevelrill_m.asc
       	├── surret_m.asc
       	├── widthrill.asc 
    	├── cinfil_m3.asc
    	├── crain_m3.asc
    	├── volrest_m3.asc
  	├── massbalance.asc
  	├── hcrit.asc
        ├── reachfid.asc
        ├──  state.asc
    ├── temp
       	├── stream.csv 
       	├── cvrill_m3.asc
       	├── cvsheet_m3.asc
       	├── mwlevelrill_m.asc 
       	├── surret_m.asc
       	├── widthrill.asc 	
    	├── cinfil_m3.asc	
    	├── crain_m3.asc	
```

**Comment by landam** [comment]
## Core

## Control

## Temp

crillvout_m3.asc
- [ ] csheetvoutm3.asc
- [ ] cvin_m3.asc
- [ ] mqrill_m3_s.asc
- [ ] mqsheet_m3_s.asc
- [ ] cvrill_m3.asc
- [ ] cvsheet_m3.asc
- [ ] mwlevelrill_m.asc
- [ ] surret_m.asc
- [ ] widthrill.asc 
- [ ] cinfil_m3.asc
- [ ] crain_m3.asc
- [ ] volrest_m3.asc
- [ ] massbalance.asc
- [ ] hcrit.asc
- [ ] reachfid.asc
- [ ] state.asc

**Comment by landam** [comment]
@kavkapet csheetvoutm3 -> csheetvout_m3 ?

**Comment by landam** [comment]
@kavkapet There are also data defined in `CumulativeSubsurface`

```
   'exfiltration': CumulativeData('core', 'cExfiltr_m3'),     # 1
            # cumulative percolation volume [m3]
            'percolation' : CumulativeData('core', 'cPercol_m3'),      # 2
            # maximum water level in the subsurface soil layer [m]
            'h_sub'       : CumulativeData('core', 'mWLevelSub_M'),    # 3
            # maximum subsurface flux [m3s-1]
            'q_sub'       : CumulativeData('core', 'mQSub_m3_s'),      # 4
            # cumulative outflow volume in subsurface soil layer [m3]
            'vol_sub'     : CumulativeData('core', 'cVOutSub_m3')      # 5
```

All are written currently to the core output directory. Please review it.

**Comment by landam** [comment]
## Core

- [ ] cExfiltr_m3
- [ ] cPercol_m3
- [ ] mWLevelSub_M
- [ ] mQSub_m3_s
- [ ] cVOutSub_m3

**Comment by landam** [comment]
Questions:

* cvrill_m3 in temp or control?

**Comment by landam** [comment]
> * cvrill_m3 in temp or control?
> * cvsheet_m3 in temp or control?
> * surret_m in temp or control?
> * cinfil_m3 in temp or control?
> * crain_m3 in temp or control?
> * widthrill in temp or control?

-> control
