### ISSUE TITLE
computation region is shrunk twice

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#198]
Once computation region is shrunk when defining mask (https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/grass/data_preparation.py#L82) and later when defining `rc` and `rr` variables (https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/base/data_preparation.py#L166).

![Screenshot from 2023-07-14 09-41-56](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/d546b7a1-22ad-4176-a40b-2ddcc643d21e)

Desired solution: get rid of `rc` and `rr` variables. Masked array may be directly derived from `aoi_mask` or `mat_boundary`.

**Comment by pesekon2** [comment]
Fixed in bee8ae26991a53dbbf52267a5d464db25f63c8ab.
