### ISSUE TITLE
define point id for output points

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#227]
![MicrosoftTeams-image](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/be603673-b238-44e8-b2d9-caa35f1ef253)

**Comment by kavkapet** [comment]
if the obs point need "field with identification" thah must be individual and must have value. 
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/f798582d-46a9-41e4-8f23-c1bb485d9236)

**Comment by landam** [comment]
@kavkapet Fixed in master.

Now the computation should fail with:

```
ERROR: Incorrect values in field 'Name': duplicated values are not allowed
```

if duplicated values detected

or 

```
ERROR: Incorrect values in field 'Name': empty values are not allowed
```

if empty values found
