### ISSUE TITLE
review different color tables applied in QGIS

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#230]
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/a44bee00-2bab-4731-b598-4e1b0b7a2802)

**Comment by pesekon2** [comment]
Your Windows behaviour happens to me on my English linux:

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/17025405/c5c5035e-6394-49cf-b483-64e6d2210087)
