### ISSUE TITLE
DEM resolution differs from processing spatial resolution

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#256]
preprocessing change (sometimes) resolution of rasters.
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/83293552-1a93-40f3-86c2-342078caa99d)
in AG is here during creation aoi_mask (in AG)
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/d170aef0-bca7-4af0-b5c1-1fb02f840114)
is need to check GridGlobals.dy
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/cf159be4-1b03-45a0-a293-84feed7b7fa8)
Grass/Qgis has no "dem_aoi"

@pesekon2 I can prepare data for DS plot after this issue

**Comment by kavkapet** [comment]
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/c7dd0e27-dd70-47c0-9d8b-6b6dd5c84742)

**Comment by kavkapet** [comment]
GridGlobals.r
GridGlobals.s

is still used? why? and is sure, that is sam as resolution as x/y?

**Comment by landam** [comment]
> GridGlobals.r GridGlobals.s
> 
> is still used? why? and is sure, that is sam as resolution as x/y?

r is number or rows vs dx is cell size (x axis)

**Comment by landam** [comment]
> here is used "new resolution"...GridGlobals.dy,GridGlobals.dx, ![image](https://user-images.githubusercontent.com/26659753/276276722-c7dd0e27-dd70-47c0-9d8b-6b6dd5c84742.png)

problem is here: https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/base/data_preparation.py#L883

It seems that ArcGIS is producing clipped DEM (`dem_aoi`) from input DEM (`dem`) with slightly different resolution.

**Comment by kavkapet** [comment]
resolution of dem_aoi are from aoi_mask and for this "GridGlobals.dy" is used to define resolution. Is any option how prit GridGlobals.dy in AG?
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/ad4680ab-ec58-4730-aac4-0911159ce3b2)
