### ISSUE TITLE
what is NoDataInt

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#263]
What is a variable named `NoDataInt` defined [here](https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/core/general.py#L66)? How does it differ from `NoDataValue` (which is an integer too)? Isn't it just some remnant that we should delete?

@landam? @jerabekjak? @kavkapet?

**Comment by landam** [comment]
@pesekon2 We can delete this variable...
