### ISSUE TITLE
qgis plugin: initial phase (import input data)

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#28]
QGIS plugin must create temporal GRASS location and import input data before computation.

Inspiration:

* QGIS processing (https://github.com/qgis/QGIS/tree/master/python/plugins/processing/algs/grass7) 
* Soils plugin: https://github.com/ctu-geoforall-lab/qgis-soil-erosion-plugin/tree/master/pyerosion

Or alternatively:

```
import grass.script as gs
import sys
print (sys.argv[1])
# gs.run_command('v.import', input=sys.argv[1], output='xxx')
print (gs.gisenv())
```

-> 

```
grass -c EPSG:5514 /tmp/test2 --exec python test.py vstup1
```

**Comment by landam** [comment]
@kalator @pikorcik What's state of this issue?

**Comment by landam** [comment]
see related #18

**Comment by pikorcik** [comment]
My fault, I didn't push my last commit. Now data should be imported from QGIS to Grass.

**Comment by landam** [comment]
OK, so I am taking liberty to close this issue.
