### ISSUE TITLE
raise error if .ini file does not exist

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#29]
if assign --indata file in cmd execution does not exist. Incorrect error is raised

Error raised:
ConfigParser.NoSectionError: No section: 'Other'

should be something line 
IncorrectInitFile: file 'somefile ' is does not exist

**Comment by landam** [comment]
```
./bin/start-smoderp2d.py --typecomp roff --indata tests/test.inix
ERROR: tests/test.inix does not exist
```
