### ISSUE TITLE
Rills in reference quicktests

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#295]
State remained zero in the calculations bellow. Also, the results from rills are all zero. Is that correct? 
```
tests/data/reference/quicktest_rill
```
```
tests/data/reference/quicktest_stream_rill
```
Rills occurred when I increased the rainfall intensity. So maybe we need to change the reference rainfall(?)

**Comment by pesekon2** [comment]
I have the same experience as @jerabekjak for GRASS/QGIS provider as well as for CMD (the quickest you are referring to) and would upvote the solution by increasing the rainfall intensity. But @kavkapet said that he got rills when running it in ArcGIS. Correct, @kavkapet?

**Comment by kavkapet** [comment]
confirm, I have rill in AGprovider
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/c467f04a-4bdb-42ee-9d28-0e3c4395a4f8)
 data is here and you have there outputs form AG (also points) and you have there also .save form the same data
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/00f3fd16-7460-4ae0-8ecc-b832945a0d13)

**Comment by pesekon2** [comment]
It was found that ArcGIS uses some huge rainfall after its value changes, about 50 times bigger than it should be. Therefore, this is no issue that the rills are not created with the quicktest data. However, the finding is that the quicktest data should be updated (e.g., raising the rainfall) to include also rills.
