### ISSUE TITLE
Question on the necessity of a loop in TimeStep.do_flow

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#30]
In [TimeStep.do_flow](https://github.com/storm-fsv-cvut/smoderp2d/blob/f63f2793ed55aab7ff7df489b4886ca7a5e214bc/smoderp2d/time_step.py#L27) is a loop through all the elements in `surface.arr`. But the whole method returns only `potRain`, which is computed before the time-consuming loop. So the question is: Is there any reason for the loop? Couldn't it be deleted? 

The method also doesn't change any variable of the TimeStep object and my experiments didn't show any change in objects taken as parameters if that was the reason behind. But of course, there can be something I am missing.

**Comment by landam** [comment]
@pesekon2 @jerabekjak What's state of this issue?

**Comment by pesekon2** [comment]
I think we can close this issue as the loop is run for some specific data (e.g. it is necessary). 

But I would like to raise a connected question here: What if we replace this loop with matrix operations? Is it possible, or must be the state-changing operations (for example changing variables of the `Surface` object) done in the loop?

**Comment by jerabekjak** [comment]
Agree with @pesekon2, close the issue.
Not sure about the second question of @pesekon2 . First thought is: it has to be in loop. Second thought: but maybe not...? I'll think about it...

**Comment by pesekon2** [comment]
@jerabekjak: Okay, cool. Lemme know about your brainstorming then. Because in case it has to be run in loop and variables are changed every time, the parallelization of this part doesn't make sense at all (we still can parallelize the computations inside the each loop, but I am afraid that this is a bit overkill, because it is pretty time-consuming to convert them to tensors and share between different CPUs and even more to transfer them to the GPU memory).
