### ISSUE TITLE
unable to process txt input in ArcGIS

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#31]
Input file: 028_m+STD_IC2_nL_Re_IL_SL

```
Computing intersect of input data...
(u' ', u' ', u' ', 0, 0, 0, u' ', u' ', u' ', u' ', u' ')
Invalid input for data preparation: Values in soilveg tab are not correct (field 'k': empty value found in row 1)
```

See: https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/arcgis/data_preparation.py#L217

**Comment by kalator** [comment]
Older versions of ArcMap are unable to parse data from txt table correctly. Works in ArcMap 10.6.
