### ISSUE TITLE
move_stream.csv, point and line nonraster data cliped in computation domain from TMP/control to main output folder

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#343]
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/65d07653-106d-45de-babd-158e897529f8)

* as you can see, stream.csv and stream aoi with summary outputs are in temp folder, moved to main folder, please.

* And also point_aoi (now only in ArcGIS provider :( ) are tmp folder
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/d41649aa-d06a-4778-8ca8-1baa0968d31b)

**Comment by kavkapet** [comment]
why is poins_aoi only in AG?

**Comment by pesekon2** [comment]
Decision: import also `point_aoi` (`control`) and `stream_aoi` (`core`) into QGIS. Connect `stream_aoi` with `stream.csv`.

**Comment by landam** [comment]
> why is poins_aoi only in AG?

@kavkapet I found `points_aoi` in temp as expected. 

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/5683186/5b8c088e-4822-4d01-930d-9ae58627b32d)

**Comment by landam** [comment]
@kavkapet `343-streams-core` branch ready for review.
