### ISSUE TITLE
Unnecessary size of array

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#355]
In `smoderp2d/smoderp2d/core/stream.py` variables [1] do not need to have the size of r and c. It could be one-digit number. There is no benefit of using arrays for calculations in streams. Could you check it @pesekon2 ?

[1] https://github.com/storm-fsv-cvut/smoderp2d/blob/cd4352fc4fac7c12d681b5a3083f8f83052e4f8b/smoderp2d/core/stream.py#L32-L73

**Comment by pesekon2** [comment]
Thanks, I didn't know about this. I have some TODOs in the code about some more (`dt`) but all my previous tests ended up either in crashing or slowing down the computation (speed vs memory problem). I will try it with these and think about some smarter ways.

Please, if you could prepare a checklist of variables that should undergo this de-matrixing (unless it's inly those four), I could start proceeding step by step.

**Comment by jerabekjak** [comment]
Maybe this is just fine. Maybe we can sacrifice some memory for the sake of shorter computation time.

**Comment by pesekon2** [comment]
@jerabekjak: I was either wrong or just lying. A current test has shown that multiplying (maybe other operations were not so efficient?) is actually one percent faster for the scalar-matrix combination than for the matrix-matrix combination. So we are able to save some memory, make the computations a few µs faster, and make everything more readable and understandable for debugging. I have already changed the `dt` and `total_time` ones and will proceed with the variables step by step as I will test everything if there is no overhead time (creating scalar from matrix) included.

If you find some more variables that should be dematrixed, please feel free to update the first post.

```python
> import numpy as np
> a = np.ones((10000, 10000))
> %timeit a * a
239 µs ± 210 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
> %timeit 1.0 * a
237 ms ± 56 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
