### ISSUE TITLE
arcgis: store all results in filegdb

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#36]
Currently only some results are stored in FileGDB. For rest of results, Esri Shapefile format is used.

**Comment by landam** [comment]
@kalator What's status of this issue?

**Comment by landam** [comment]
@kalator When done please merge into master. Or should I tested in your branch?

**Comment by landam** [comment]
It seems to fail on line 221 (tested with ArcGIS Pro). Also there are some shapefiles created in `output` dir. @kalator Will you have time to work on this issue in next days?

**Comment by pikorcik** [comment]
@landam Now should be all shapefiles stored in two gdb. And our branch is merged to master.

**Comment by landam** [comment]
cool, thanks! I took liberty to remove `arcgis_refactor_kalator` working branch.

**Comment by landam** [comment]
Seems to work closing.
