### ISSUE TITLE
computing_area

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#387]
why this is possible? In ouptpust is diffrent pixel in computation (see pink points)

![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/06c92fbd-7264-4f3d-94ed-65003bfea052)

**Comment by kavkapet** [comment]
![image](https://github.com/storm-fsv-cvut/smoderp2d/assets/26659753/74398f3c-f23e-42af-a75f-6cca27e303d6)

**Comment by landam** [comment]
Task: check how mwlevel_m is computed (this layer don't have some pixels on edges)

**Comment by kavkapet** [comment]
arcpy.ImportToolbox(r"D:\0_Smoderp\_2_D\0_skript\_git_CVUT\smoderp2d\bin\arcgis\SMODERP2D.pyt")
arcpy.ImportToolbox(r'D:\0_Smoderp\_2_D\0_skript\_git_CVUT\smoderp2d\bin\arcgis\SMODERP2D.pyt','')
arcpy..SMODERP2D(
    inputSurfaceRaster=r"D:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\DEM_fill.tif",
    inputSoilPolygons=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\Soil_ZKCl_clip.shp",
    soilTypefieldName="Soil",
    inputLUPolygons=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\LandUse_ZK_clearQG.shp",
    LUtypeFieldName="LU1_code",
    inputRainfall=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\1-12-02-081_N100_A.txt",
    maxTimeStep=5,
    totalRunTime=380,
    inputPoints=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\subcatch_points.shp",
    inputPointsFieldName="Id",
    soilvegPropertiesTable=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\SoilVeg_IC2_zk.dbf",
    soilvegIDfieldName="soilveg",
    streamNetwork=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\streams.shp",
    streamChannelShapeIDfieldName="channel_id",
    channelTypesTable=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\streams_shape.dbf",
    flowRoutingType="single",
    generateTempData=True,
    outDir=r"H:\2_granty_projekty\2_Bezici\2022_RAGO\01_reseni_projektu\02_SmoderpSimulace\Svodnice_velvary\_out\subcatch_points_380",
    waveType="kinematic"
)
