### ISSUE TITLE
check box - output type AG

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#56]
only check box for .save are aviable. 
can be chcek boxs for "additional" or/and "control" results.
![image](https://user-images.githubusercontent.com/26659753/66379012-f1b3fa80-e9b4-11e9-889a-f231e31c6e93.png)

**Comment by landam** [comment]
Can you provide details? Control/Temp/Core output data are stored in output directory anyway.

**Comment by landam** [comment]
- [ ] Do not delete temporary data

**Comment by jerabekjak** [comment]
see #126

**Comment by landam** [comment]
Missing: ArcGIS refuses to remove temporary data if removal requested.

**Comment by landam** [comment]
This issue can be closed to my understanding.
