### ISSUE TITLE
reduce duplicated variables dx/dy vs spix/vpix

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#60]
Currently two pairs of variables are used to stored x/y spatial resolution (pixel width/height).

1) `dx` is computed from `pixel_area` (1)
2) `dy` is set from `dx` (we are assuming square pixel)
3) `spix/vpix` is determined from DEM resolution (pixel can be rectangular) (2)
3) `pixel_area` is computed from `spix/vpix`

So the input data's x/y resolution can be different, but result will be always based on the same x/y resolution. Is it expected?

@jerabekjak @kavkapet Do we really need these two pairs of variables? 
 
(1) https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/base/__init__.py#L174
(2) https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/arcgis/data_preparation.py#L315

**Comment by landam** [comment]
@jerabekjak Any opinion? Thanks!

**Comment by jerabekjak** [comment]
@landam 
I would prefer to use the method used in the link (2) in https://github.com/storm-fsv-cvut/smoderp2d/issues/60#issue-519923186. It is more generic for case of no square raster cell. 
The spix/vpix is used in the code much more compated to  dx/dy. (ag vpix smoderp2d/* / ag dx smoderp2d/*). But I would still prefer dx/dy.

**Comment by landam** [comment]
Suggestion:

* `dx/dy` is determined from DEM resolution (pixel can be rectangular) (2)
* `pixel_area` is computed from dx/dy

Remove `spix/vpix` references.
