### ISSUE TITLE
Output Temp

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#62]
allowed temp files from computning + clean up of hydrographs

**Comment by kavkapet** [comment]
fl_dirtemp.asc - empty raster in code - deleted or moved to other dir
control point - are missed in core. only impute points  are in temp. some point are between computing domain and "impute domain" - see picture down
stream_vector - the same missed in the core and are not on the end of computing domain

stream.csv - are out of the structure od outputs and the header are without units (# FID;b;m;rough;q365;V_out_cum;Q_max)


![image](https://user-images.githubusercontent.com/26659753/69061909-5b92db80-0a1a-11ea-9e26-c998ac8e08c2.png)

**Comment by jerabekjak** [comment]
I pull all remaining computer cumulative and maximum arrays to the control folder. see commit 8af2ca99f153df4f0225699b3fd40ae8ff7e0741

**Comment by jerabekjak** [comment]
@kavkapet ja sem dal vse do adresare control. ne temp. proc? protoze myslim, ze puvodne to tam bylo minene. argument byl ze to neni nejaky docasny mezivydledek (temp), ale neco je vysledek, ale chces to videt jen nekdy.

**Comment by jerabekjak** [comment]
Branch is assigned to this issue see [1]
[1] https://github.com/storm-fsv-cvut/smoderp2d/tree/issue_62_Output_Temp

**Comment by jerabekjak** [comment]
move points to core dir see commit 596e6fa2fb117e05be77d70cbdd4d97e245f15fc
