### ISSUE TITLE
internal poit and stream to output

### ISSUE THREAD

**Issue by kavkapet** [storm-fsv-cvut/smoderp2d#74]
Internal point (shp layer) save to core output
stream - part in computed area (with added outputs for each segment - other issue from Dec 11) save also to core output
output point data (.dat) save also to core output or subfolder of core

**Comment by landam** [comment]
Avoid 'core' subdir.

```
output/
output/temp
output/control
```

**Comment by jerabekjak** [comment]
see commit 3c93b9b57b2123e6b996df6af28901fb8c0463af

**Comment by jerabekjak** [comment]
pull into master in commit 1aebfe32c9253eb38c1b8f0a76a49729d6d6a7bc
