### ISSUE TITLE
internal counrant config 

### ISSUE THREAD

**Issue by jerabekjak** [storm-fsv-cvut/smoderp2d#77]
Add config file into smodel structure so curious user can change the courant criterion margins. 
The cfg file can be read in the constructor of class courant.Courant. (as it is shown in the example)
eg:
```
smoderp2d/
   ...
   courant.py
   courant.cfg
   ....
```

**Comment by jerabekjak** [comment]
I'll put more config to the model in this issue.
The new internal config will be `advanced.cfg`. 
In `advanced.cfg` , there fill be courant criterion config and some more advanced config.
smoderp2d/
   ...
   advanced.cfg
   ....

**Comment by kavkapet** [comment]
done in https://github.com/storm-fsv-cvut/smoderp2d/pull/126

**Comment by kavkapet** [comment]
done in https://github.com/storm-fsv-cvut/smoderp2d/pull/126
