### ISSUE TITLE
GRASS sample computation fails (Unable to reach inflow)

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#81]
Run `r.smoderp2d` fails with:

```
ERROR: Unable to reach inflow. Index 4 out of range (number of reach 3)
```

**Comment by jerabekjak** [comment]
@landam you can try to simplify, the stream network in the input data. Use only one line as a stream instead of the polyline feature, for example. Then you can try adding more lines, and see when it crashes.

**Comment by landam** [comment]
@jerabekjak The reason is confirmed. The clipped streams contains original FID (in red), in this case, 1, 2, 5.

![streams_clip](https://user-images.githubusercontent.com/5683186/80498425-fe596980-896b-11ea-821a-b5c369f9129a.png)

**Comment by landam** [comment]
@jerabekjak fid should start always with zero not one, right. See hack in https://github.com/storm-fsv-cvut/smoderp2d/blob/master/smoderp2d/providers/arcgis/stream_preparation.py#L306

**Comment by jerabekjak** [comment]
@landam well, the logic of the reaches handling is that FID start at 0 and the increment is always 1. So, the FID can also be used to refer to an element in python list. As far as I understand, ArcGIS works the way that the FID always start at zero and always has an increment of 1, even if you slip out some middle FID, like in our case.
