### ISSUE TITLE
Review 1000 -> Globals.streams_flow_inc

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#83]
The check list is based on https://github.com/storm-fsv-cvut/smoderp2d/pull/82#issuecomment-622561674. I'll review it as soon as possible. 

- [ ] smoderp2d/core/general.py:186:    streams_flow_inc = 1000
- [ ] smoderp2d/core/vegetation.py:26:        mat_pi = Globals.get_mat_pi() / 1000.0
- [ ] smoderp2d/io_functions/hydrographs.py:54:                if Globals.get_mat_stream_reach(l, m) >= 1000:
- [ ] smoderp2d/io_functions/post_proc.py:71:            if (finState[i][j] >= 1000):
- [ ] smoderp2d/io_functions/post_proc.py:130:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/io_functions/post_proc.py:154:                # if (finState[ii][jj]>=1000):
- [ ] smoderp2d/io_functions/post_proc.py:256:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/io_functions/post_proc.py:267:                # if (finState[i][j] >= 1000) :
- [ ] smoderp2d/processes/rainfall.py:71:                    y1 = float(z[1]) / 1000.0  # prevod na metry
- [ ] smoderp2d/providers/arcgis/data_preparation.py:113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"
- [ ] smoderp2d/providers/arcgis/stream_preparation.py:202:        1000 in return numpy array) or not (number 0 in return numpy
- [ ] smoderp2d/providers/arcgis/stream_preparation.py:218:        #     "NoDataValue 1000", stream_seg, "DATA"
- [ ] smoderp2d/providers/base/__init__.py:212:        Globals.mat_reten = -1.0 * data['mat_reten'] / 1000
- [ ] smoderp2d/providers/base/__init__.py:395:                if finState[i][j] >= 1000:
- [ ] smoderp2d/providers/base/__init__.py:406:                if  int(surface_array[i][j].state) >= 1000 :
- [ ] smoderp2d/providers/base/data_preparation.py:423:                        hcrit_tau = hcrit_v = hcrit_flux = 1000
- [ ] smoderp2d/providers/base/output.py:36:                    if fs[i][j] >= 1000:
- [ ] smoderp2d/providers/grass/stream_preparation.py:203:        1000 in return numpy array) or not (number 0 in return numpy
- [ ] smoderp2d/providers/grass/stream_preparation.py:221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(
[

**Comment by landam** [comment]
```
ag 1000 --py
smoderp2d/processes/rainfall.py
71:                    y1 = float(z[1]) / 1000.0  # prevod na metry

smoderp2d/core/vegetation.py
29:        mat_pi = Globals.get_mat_pi() / 1000.0

smoderp2d/core/general.py
210:    streams_flow_inc = 1000

smoderp2d/io_functions/hydrographs.py
57:                if Globals.get_mat_stream_reach(l, m) >= 1000:

smoderp2d/io_functions/post_proc.py
71:            if (finState[i][j] >= 1000):
130:                # if (finState[i][j] >= 1000) :
154:                # if (finState[ii][jj]>=1000):
256:                # if (finState[i][j] >= 1000) :
267:                # if (finState[i][j] >= 1000) :

smoderp2d/providers/grass/stream_preparation.py
203:        1000 in return numpy array) or not (number 0 in return numpy
221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(

smoderp2d/providers/arcgis/data_preparation.py
113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"

smoderp2d/providers/arcgis/stream_preparation.py
202:        1000 in return numpy array) or not (number 0 in return numpy
218:        #     "NoDataValue 1000", stream_seg, "DATA"

smoderp2d/providers/base/__init__.py
246:        Globals.mat_reten = -1.0 * data['mat_reten'] / 1000
440:                if finState[i][j] >= 1000:
451:                if  int(surface_array[i][j].state) >= 1000 :

smoderp2d/providers/base/output.py
36:                    if fs[i][j] >= 1000:

smoderp2d/providers/base/data_preparation.py
419:                        hcrit_tau = hcrit_v = hcrit_flux = 1000
```

**Comment by jerabekjak** [comment]
`smoderp2d/processes/rainfall.py
71:                    y1 = float(z[1]) / 1000.0  # prevod na metry

smoderp2d/core/vegetation.py
29:        mat_pi = Globals.get_mat_pi() / 1000.0`
This has s physical meaning. Should not be changed

**Comment by jerabekjak** [comment]
```
smoderp2d/providers/grass/stream_preparation.py
203:        1000 in return numpy array) or not (number 0 in return numpy
221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(

smoderp2d/providers/arcgis/data_preparation.py
113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"

smoderp2d/providers/arcgis/stream_preparation.py
202:        1000 in return numpy array) or not (number 0 in return numpy
218:        #     "NoDataValue 1000", stream_seg, "DATA"
```
Those lines has some GIS meaning. Or the 100 is set there. This should not be changed.

**Comment by jerabekjak** [comment]
```
smoderp2d/providers/base/data_preparation.py
419:                        hcrit_tau = hcrit_v = hcrit_flux = 1000
```
This also has a physical meaning. Should not be changed.

**Comment by jerabekjak** [comment]
see commit: 6a05e26d455b216d09f11f74509fb04c58591c84

**Comment by jerabekjak** [comment]
ag 1000 smoderp2d:
```
smoderp2d/io_functions/post_proc.py <- POSTPROCESSING WILL BE MOVED TO INIDIVIDUAL PROVIDERS IN PULL REGUEST #138
71:            if (finState[i][j] >= 1000):
130:                # if (finState[i][j] >= 1000) :
154:                # if (finState[ii][jj]>=1000):
256:                # if (finState[i][j] >= 1000) :
267:                # if (finState[i][j] >= 1000) :

smoderp2d/providers/arcgis/stream_preparation.py <- THIS IS IN COMMENTS CANNOT BE CHANGED TO VARIABLE
202:        1000 in return numpy array) or not (number 0 in return numpy
218:        #     "NoDataValue 1000", stream_seg, "DATA"

smoderp2d/providers/arcgis/data_preparation.py <- THIS THE NUMBER IS NOT 1000 
113:            dem_copy, "VALUE", "-100000 100000 1", dem_mask, "DATA"

smoderp2d/providers/grass/stream_preparation.py <- THOSE 1000s ARE IN COMMENT CANNOT BE CHANGED TO VARIABLES
203:        1000 in return numpy array) or not (number 0 in return numpy
221:               # expression='{o} = if(isnull({i}), 1000, {i})'.format(

smoderp2d/providers/base/__init__.py
246:        Globals.mat_reten = -1.0 * data['mat_reten'] / 1000 <- UNIT CONVERSION

smoderp2d/providers/base/data_preparation.py
419:                        hcrit_tau = hcrit_v = hcrit_flux = 1000 <- DIFFERENT MEANING THAT STREA_FLOW_INC

smoderp2d/core/general.py
210:    streams_flow_inc = 1000 <- HERE THE VARIABLE IS CREATED

smoderp2d/core/vegetation.py
29:        mat_pi = Globals.get_mat_pi() / 1000.0 <- UNIT CONVERSION

smoderp2d/processes/rainfall.py
71:                    y1 = float(z[1]) / 1000.0  # prevod na metry  <- UNIT CONVERSION


```
@landam @kavkapet This issue can be cloaed.

**Comment by jerabekjak** [comment]
see commit 71deecd1659affe136f18707a01935317efccaab
