### ISSUE TITLE
nogis provider fails when using Python from ArcGIS 10.8

### ISSUE THREAD

**Issue by landam** [storm-fsv-cvut/smoderp2d#92]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/5683186/100630529-f3641e80-332a-11eb-9593-84d49ce30528.png)

**Comment by landam** [comment]
ArcGIS 10 comes with very old numpy (1.9)
![Uploading VirtualBox_Windows 10 (ArcGIS Pro)_30_11_2020_16_48_48.png…]()

**Comment by landam** [comment]
The `numfromtxt()` has no encoding parameter in numpy 1.9 version, https://docs.scipy.org/doc/numpy-1.9.3/reference/generated/numpy.genfromtxt.html

**Comment by landam** [comment]
@pesekon2 Can you fix it easily? If not I would drop support of old numpy versions (related only to ArcGIS 10 which is no dependency for nogis provider). @kavkapet

**Comment by pesekon2** [comment]
Not easily. And not optimally. The change would require quite some coding and most importantly it would bring two things to the code:

* everything will be done in multiple loops through the two of the CSV files - slower and inefficient
* we would either force the order of the columns to the user or do some unintuitive jumps when parsing these CSV files

As I said, I can do so. But I would recommend to use NumPy 1.14.0 or newer.

**Comment by landam** [comment]
@pesekon2 Note that in Ubuntu 18.04 (which is still supported by eg. UbuntuGIS) there is 1.13, https://packages.ubuntu.com/bionic/python3-numpy

**Comment by landam** [comment]
But generally speaking I am fine with numpy >= 1.14 (this implies to nogis provider anyway). Keeping this issue open. NoGIS provider should check required numpy version.

**Comment by landam** [comment]
Version 2.0.0 will not support Python2, closing.
