### ISSUE TITLE
change column names in CSV files for the NoGIS provider from Czech to English

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#93]
```
vodorovny prumet stahu[m];prevyseni[m];povrch;puda;sklon
```

**Comment by landam** [comment]
Update `tests/data/nogis/data1D.csv`

**Comment by jerabekjak** [comment]
```
-> % ag vodorovny  .
bin/wps/request.xml
8:        <wps:ComplexData mimeType="text/csv"><![CDATA[vodorovny prumet stahu[m];prevyseni[m];povrch;puda;sklon

smoderp2d/providers/nogis/__init__.py
182:        data['r'] = self._compute_rows(joint_data['vodorovny_prumet_stahu[m]'],
317:            joint_data['vodorovny_prumet_stahu[m]'],
326:                slope_segment['vodorovny_prumet_stahu[m]'],

tests/data/nogis/data1D.csv
1:﻿vodorovny prumet stahu[m];prevyseni[m];povrch;puda;sklon
```

**Comment by jerabekjak** [comment]
first question 
in `vodorovny prumet stahu[m];prevyseni[m];povrch;puda;sklon` is the sklon used? I cant change the slope with the sklon, 
The slope in the code changes only if I change the `prevyseni`..

**Comment by pesekon2** [comment]
No, `sklon` is not used anywhere in the code. I think that we can even get rid of that in the test data.

**Comment by jerabekjak** [comment]
So my suggetions are:
`horizontal length [m];  elevation change [m]; soil cover; soil type`
or 
`horizontal length [m];  vertical distance [m]; soil cover; soil type`
or 
`horizontal projection [m];  vertical distance [m]; soil cover; soil type`

@kavkapet ?

slope is calculated from the first 2 columns.

**Comment by kavkapet** [comment]
horizontal projection [m]; vertical distance [m]; surface protection; soil type
