### ISSUE TITLE
change structure of .ini config files

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#98]
Here are few `.ini` file change proposals to be considered:

- [ ] Input data are currently in the section `other`. That seems a bit weird to me. What about creating section `data` or `input` and moving inputs and rainfall (currently alone in section `rainfall` as `file` - I propose to rename it to `rainfall` then) there? 
- [ ] When working with pickle files, they are called `other` - `config`. Shall they really be called `config`?

**Comment by landam** [comment]
See `config_issue_98` branch:

- [ ] update `tests/test.ini` (based on `tests/quicktest.ini`)
- [ ] review code

**Comment by landam** [comment]
Logging level implemented in 26f3f8b1e5188f6ebb5ab659c57bcaba087dd13b
