### ISSUE TITLE
move core outputs one dir higher

### ISSUE THREAD

**Issue by pesekon2** [storm-fsv-cvut/smoderp2d#99]
According to @kavkapet, there should be no `core` directory created by SMODERP1D. These outputs should be created one level higher.

**Comment by pesekon2** [comment]
@kavkapet: Are you sure that these values are written one directory higher in other providers than the NoGIS one? Because when I try to run SMODERP2D with our test data, I also get the `core` directory.

In such case, should I change all of the processors to write data one directory higher, or should we keep the `core` directory?

**Comment by landam** [comment]
This change is also related to smoderp2d process since 'core' directory is also created.

**Comment by landam** [comment]
Already done.
